title: "Iris & Gian Luca"
description: "Our wedding in Sicily"
baseurl: ""
url: ""
permalink: pretty
city: "Noto (SR)"
region: "Sicily"
country: "Italy"


wedding_date: 2026-05-30
venue_name: "Pantanelli di Vendicari"
venue_address: "c.da roveto di vendicari 96017 Noto (SR), Italy"
venue_map_embed_url: "https://www.google.com/maps?q=Farm+Pantanelli+Vendicari&output=embed"
townhall_name: "Palazzo Ducezio"
townhall_address: "Piazza Municipio, 1 - 96017 Noto (SR), Italy"
townhall_map_embed_url: "https://www.google.com/maps?q=Palazzo+Ducezio&output=embed"


# RSVP handling (Formspree example). Replace with your endpoint or Netlify forms.
rsvp_form_action: "https://formspree.io/f/yourFormID"
rsvp_deadline: 2026-04-25

# Registry
revo_bank:
  name: "Gian Luca Fiasco"
  iban: "GB46 REVO 0099 7045 0597 25"
eur_bank:
  name: "Iris Michalopoulou Kandri"
  iban: "GR...."
gbp_bank: 
  name: "Gian Luca Fiasco"
  iban: "GB...."

collections:
  pages:
    output: true


markdown: kramdown
theme: null
plugins: []
